apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eirel-consumer
  namespace: eirel-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - chat.eirel.example.com
      secretName: eirel-production-consumer-tls
  rules:
    - host: chat.eirel.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: consumer-chat-api
                port:
                  number: 8080
