apiVersion: v1
kind: Service
metadata:
  name: owner-api
  namespace: eirel-control-plane
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8000"
spec:
  type: NodePort
  selector:
    app: owner-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30020
